[package]
name = "dm_space_echo"
version = "0.1.0"
edition = "2021"

[dependencies]
lv2 = { version = "0.6.0", features = ["minimal_plugin"] }
space_echo = { path = "../space_echo" }

[lib]
crate-type = ["cdylib"]